
# This clones additional zsh plugins to the `oh-my-zsh` custom plugins directory
---
- hosts: flammel
  tasks:
    - name: Clone zsh plugins
      shell: "git clone {{ item }}"
      args:
        chdir: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins"
      loop:
        - https://github.com/zsh-users/zsh-autosuggestions
        - https://github.com/zsh-users/zsh-syntax-highlighting
        - https://github.com/zsh-users/zsh-completions.git
        - https://github.com/djui/alias-tips.git
        - https://github.com/lukechilds/zsh-better-npm-completion
        - https://github.com/akarzim/zsh-docker-aliases.git

