
---
- hosts: flammel
  tasks:

    # - name: Remove nvim config
    #   file:
    #     path: "/home/{{ ansible_user }}/.config/nvim"
    #     state: absent

    - name: Clone AstroVim
      git:
        repo: "https://github.com/AstroNvim/AstroNvim"
        dest: "/home/{{ ansible_user }}/.config/nvim"
        clone: yes
        update: yes

  # After this, run `nvim +PackerSync`
  # and follow the instructions in the repo README
