---
- hosts: localhost
  tasks:

    # - name: Remove nvim config
    #   file:
    #     path: "/home/{{ ansible_user }}/.config/nvim"
    #     state: absent

    - name: Clone AstroVim
      git:
        repo: "https://github.com/AstroNvim/AstroNvim"
        dest: "/home/{{ ansible_user }}/.config/nvim"
        clone: yes
        update: yes

    - name: Install vim-plug (so I can install vim plugins)
      shell: "sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"

  # After this, run `nvim +PackerSync`
  # and follow the instructions in the repo README

  # TODO: `user` config should live in `dotfiles`, so re-run stow after this so it's linked again
